---
AWSTemplateFormatVersion: '2010-09-09'

Resources:
  TylergohlCom:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: "Hosted zone for tylergohl.com"
      Name: tylergohl.com
  DefiOnboardingComRSG:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref TylergohlCom
      RecordSets:
      - Name: aws.tylergohl.com
        Type: NS
        TTL: '600'
        ResourceRecords:
          - ns-1769.awsdns-29.co.uk
          - ns-500.awsdns-62.com
          - ns-1231.awsdns-25.org
          - ns-593.awsdns-10.net
