name: push

on:
  push:
    branches:
      - main

jobs:

  get-stack-list:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Get list of files in templates folder, remove their extensions (sed statement), and convert to JSON (jq statement)
      # Then set the result as an output to be used by follow up jobs
      - id: set-matrix
        run: echo "::set-output name=matrix::$(ls ./templates -1 | sed 's/\.[^.]*$//' | jq -R -s -c 'split("\n")[:-1]')"

  deploy:
    name: Create or Update Stacks
    runs-on: ubuntu-latest
    needs: get-stack-list
    strategy:
      matrix:
        stack: ${{ fromJSON(needs.get-stack-list.outputs.matrix) }}
      max-parallel: 8 # This setting can be adjusted if API limits are hit.
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Create or Update Stacks
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: dns-${{ matrix.stack }}
          template: ./templates/${{ matrix.stack }}.yaml
          no-fail-on-empty-changeset: "1"
